name: Test build step

on: [ push, workflow_dispatch ]
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run build Action
        uses: ./build 
        with:
          favorite-color: ${{ secrets.FAVORITE_COLOR }}
